name: slatable_mobile
description: Self tapes simplified
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  top_snackbar_flutter: ^1.0.0
  loading_overlay: ^0.3.0
  flutter_staggered_grid_view: ^0.4.0

  # video
  flutter_ffmpeg: ^0.4.0

  # local storage
  hive: ^2.0.3
  path_provider: ^2.0.1

  # state management
  flutter_riverpod: ^0.14.0+1

  bloc: ^7.1.0
  flutter_bloc: ^7.2.0


  #color

  hexcolor: ^2.0.5

  #font
  google_fonts: ^2.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  # splash
  flutter_native_splash: ^1.2.1
flutter_native_splash:
  image: assets/icons/logoo.png
  color: "#000000"


flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

fonts:
  - family: Causten
    fonts:
      - asset: assets/fonts/Causten-Regular.otf
        weight: 500
